#!/bin/bash
#arvutab 10 esimese arvu summa ja liidab ainult paaris arvud
sum=0
for (( number=1; number<11; number++ ))
do
     alles=$(($number % 2))
     if [ $alles -eq 0 ]
     then
           sum=$(($sum + $number))
           echo $sum
     fi
done
echo "Summa tuli kokku: $sum"

