#!/bin/bash

#Küsib kasutajalt arvu
nano -n "Sisesta suvaline täisarv: "

read arv

arv2=$arv

#Arvutab summa
summa=0
while [ $arv -ne 0 ]; do
      alles=$(($arv % 10)) 
      summa=$(($summa + $alles))
      arv=$(($arv / 10))
done

echo "Arvu $arv2 numbrite summa on: $summa"
