#!/bin/bash

#muutujad
echo -n "Sisesta ainepunktide arv: "

read n1

echo -n "Sisesta nädalate arv: "

read n2

#Ajakulu arvutamine
aeg=`echo "scale=1;($n1*26)/$n2" | bc`

#Ümardamine
aeg_ymarda="`echo "($aeg+0.9)/1" | bc`"

echo "$aeg_ymarda"
