#!/bin/bash

#Vaatab kas arv on kaasa antud
if [ $# != 1 ]
then
        echo "Käivita skript arvuga palun"
else
        arv=$1
        final=$(($arv % 2))
        if [ $final -eq 0 ]; then
               echo "arv on paaris"
        else
               echo "arv on paaritu"
        fi
fi



