#!/bin/bash

#Andmete küsimine
echo -n "Sisesta reisijate arv: "

read reisijad

echo -n "Sisesta kohtade arv bussis: "

read kohad
#arvutada mitu bussi on vaja
vaja=$(( $reisijad / $kohad))
#arvutada palju üle jääb
inimesi=$(($reisijad % $kohad))

if test $inimesi -gt 0
then
      vaja=$(($vaja + 1))
fi
#Väljastada vastus
echo "Vaja on $vaja bussi"
